FROM python:3.6

WORKDIR /jupiter

ARG INSTALL_PROXY='--trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --proxy=127.0.0.1:8118'

RUN pip install ${INSTALL_PROXY} jupyter -U \
&& pip install ${INSTALL_PROXY} jupyterlab \
&& pip install ${INSTALL_PROXY} -U scikit-learn

EXPOSE 8888

ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--allow-root"]